In [2]:
%notebook "../numpy/numpy.ipynb"

In [2]:
import numpy
n = numpy.arange(27)

In [6]:
type(n)

In [7]:
n.reshape(3,9)

In [4]:
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [5]:
m = numpy.asarray([[123,123,12,44,26],[234,56],["Jopa"]])

In [6]:
m

array([list([123, 123, 12, 44, 26]), list([234, 56]), list(['Jopa'])],
      dtype=object)

In [7]:
print(m)

[list([123, 123, 12, 44, 26]) list([234, 56]) list(['Jopa'])]


In [8]:
type(m)

numpy.ndarray

In [10]:
import cv2

In [17]:
im_g = cv2.imread("smallgray.png", 0) # 0: as a gray scale image
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [16]:
im_c = cv2.imread("smallgray.png", 1) # 1: as a rgb-image (actually - BRG)
im_c

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

In [14]:
cv2.imwrite("newsmallgray.png", im_g)

True

### Numpy array slicing

In [18]:
print(im_g)

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


In [19]:
print(im_g[0:2])

[[187 158 104 121 143]
 [198 125 255 255 147]]


In [21]:
print(im_g[0:2,2:4])

[[104 121]
 [255 255]]


### Numpy array iterating

In [23]:
for i in im_g:
    print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [25]:
for i in im_g.T:
    print(i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [26]:
for i in im_g.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


### Stacking Numpy Arays 

In [29]:
ims = numpy.hstack((im_g, im_g)) # h for Horizontal stacking
ims

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)

In [30]:
ims = numpy.vstack((im_g, im_g)) # v for Vertical stacking
ims

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

### Splitting Numpy Arrays

In [31]:
lst = numpy.hsplit(ims, 5)

In [32]:
lst

[array([[187],
        [198],
        [209],
        [187],
        [198],
        [209]], dtype=uint8), array([[158],
        [125],
        [134],
        [158],
        [125],
        [134]], dtype=uint8), array([[104],
        [255],
        [255],
        [104],
        [255],
        [255]], dtype=uint8), array([[121],
        [255],
        [ 97],
        [121],
        [255],
        [ 97]], dtype=uint8), array([[143],
        [147],
        [182],
        [143],
        [147],
        [182]], dtype=uint8)]

In [33]:
lst[1].shape

(6, 1)

In [34]:
lst_v = numpy.vsplit(ims,3)
lst_v

[array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147]], dtype=uint8),
 array([[209, 134, 255,  97, 182],
        [187, 158, 104, 121, 143]], dtype=uint8),
 array([[198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8)]